#!/bin/bash

# Stop if error
set -e

# Get Magritte
git clone https://github.com/UCL/Magritte.git

# Enter the Magritte folder
cd Magritte

# Install dependencies
bash install.sh

# Compile Magritte for Binder
bash build.sh binder
